export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

export const OREDR_DETAILS_REQUEST = 'OREDR_DETAILS_REQUEST'
export const OREDR_DETAILS_SUCCESS = 'OREDR_DETAILS_SUCCESS'
export const OREDR_DETAILS_FAIL = 'OREDR_DETAILS_FAIL'