# Generated by Django 3.1.7 on 2021-04-11 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210411_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='countInstock',
            new_name='countInStock',
        ),
    ]
